feat: 强大灵活易用的多端CI/CD共享库流水线

diff --git a/Dockerfile.python b/Dockerfile.python
--- a/Dockerfile.python
+++ b/Dockerfile.python
@@ -1,26 +1,62 @@
-# 使用Ubuntu 作为基础镜像
-FROM ubuntu:latest
+# Use an official Python runtime as a parent image
+ARG PYTHON_VERSION
 
-# 设置Python版本
-ARG PYTHON_VERSION=3.10
-ENV PYTHONUNBUFFERED=1
+#FROM python:${PYTHON_VERSION}-slim
+FROM  ubuntu:latest
 
-# 更新包列表并安装必要的依赖
-RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g'  /etc/apt/sources.list  && apt-get update && apt-get install -y \
-    python${PYTHON_VERSION} \
-    python3-pip \
-    libglx-mesa0 \
-    && rm -rf /var/lib/apt/lists/*
-
-# 设置Python默认版本
-#RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYTHON_VERSION} 1
-RUN python -V
-
-# 安装pip并确保指向正确版本
-RUN pip3 install --upgrade pip
-
-# 设置工作目录
+# Set working directory
 WORKDIR /app
 
-# 验证安装
-RUN python3 --version && pip3 --version
+# 指定切换用户
+USER root
+
+# 设置时区
+ENV TZ=Asia/Shanghai
+RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
+
+# Set environment variables
+#ENV PIP_CACHE_DIR=/pip-cache \
+#    PIP_NO_CACHE_DIR=false \
+#    PYTHONDONTWRITEBYTECODE=1 \
+#    PYTHONUNBUFFERED=1
+
+# 挂载数据卷 docker删除后数据不丢失 docker run -v 映射
+#VOLUME $PIP_CACHE_DIR
+
+# Create pip cache directory
+#RUN mkdir -p /pip-cache && \
+#    chmod -R 777 /pip-cache
+
+# 设置非交互式安装以避免提示
+ENV DEBIAN_FRONTEND=noninteractive
+
+# 更新包列表并安装基本工具
+RUN apt-get clean && apt-get update && apt-get install -y \
+    curl \
+    wget \
+    gnupg \
+    lsb-release \
+    software-properties-common
+
+RUN python3 -V
+ARG INSTALL_PACKAGES
+# Install system dependencies and clean up
+RUN if [ -n "$INSTALL_PACKAGES" ]; then \
+         echo "动态安装依赖 $INSTALL_PACKAGES" && \
+         apt install -y --no-install-recommends $INSTALL_PACKAGES && \
+         rm -rf /var/lib/apt/lists/*; \
+    fi
+
+# Copy requirements.txt (if it exists) to calculate hash
+COPY requirements.txt* /app/
+COPY requirement.txt* /app/
+
+
+#RUN mv requirement.txt requirements.txt || true && pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
+RUN pwd && ls
+
+# Copy application code
+COPY . /app
+
+# Default command
+CMD ["python", "app.py"]
